// The browser decoder and the leader must agree bit for bit: check the TS mirror
// against the vectors generated by the Rust tests (pixelplus-core mapcode).
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
	codebook,
	codeword,
	frameFor,
	gray,
	grayInverse,
	GAP_SLOTS,
	LEAD_IN_SLOTS,
	pixelBitsFor,
	pixelOn,
	popcount,
	PREAMBLE,
	schedule,
	type Plan
} from './mapcode';

const vectors = JSON.parse(
	readFileSync(resolve(process.cwd(), '../crates/pixelplus-core/tests/fixtures/mapcode/vectors.json'), 'utf8')
);

describe('mapcode mirror', () => {
	it('matches the Rust constants and Gray code', () => {
		expect(vectors.constants.leadInSlots).toBe(LEAD_IN_SLOTS);
		expect(vectors.constants.gapSlots).toBe(GAP_SLOTS);
		expect(vectors.constants.preamble).toEqual(PREAMBLE);
		for (const [n, g] of vectors.gray) {
			expect(gray(n)).toBe(g);
			expect(grayInverse(g)).toBe(n);
		}
		expect(pixelBitsFor(2048)).toBe(11);
		expect(pixelBitsFor(2049)).toBe(12);
	});

	it('builds identical codebooks', () => {
		for (const b of vectors.codebooks) {
			const book = codebook(b.bits);
			expect(book.length).toBe(b.len);
			expect(book.slice(0, 32)).toEqual(b.first);
			expect(book[book.length - 1]).toBe(b.last);
			expect(book.reduce((s, c, i) => s + (i + 1) * c, 0)).toBe(b.weightedSum);
			for (let i = 0; i < book.length; i += 7)
				for (let j = i + 1; j < book.length; j += 5)
					expect(popcount(book[i] ^ book[j])).toBeGreaterThanOrEqual(4);
		}
	});

	it('renders identical frames', () => {
		for (const c of vectors.plans) {
			const plan = c.plan as Plan;
			expect(schedule(plan)).toEqual(c.schedule);
			c.shownTargets.forEach((k: number, i: number) => expect(codeword(plan, k)).toBe(c.codewords[i]));
			for (const s of c.samples) {
				const f = frameFor(plan, s.t);
				// Rust serializes the slot as {kind, ...fields} next to pass.
				const { pass, slot } = s.frame;
				expect(f.pass).toBe(pass);
				expect(f.slot).toEqual(slot);
				c.shownTargets.forEach((k: number, i: number) => {
					const bits = [...s.targets[i]].map((ch) => ch === '1');
					bits.forEach((on: boolean, px: number) =>
						expect(pixelOn(plan, f, k, px), `t=${s.t} k=${k} px=${px}`).toBe(on)
					);
				});
			}
		}
	});
});
