// GENERATED from tts/pixelplus_tts/data/pronunciations.txt (tested fixes from tlchandler/fpp-voices).
// Regenerate if that file changes. Format: [word, say]; say between slashes is IPA.

export const BUILTIN_PRONUNCIATIONS: readonly (readonly [string, string])[] = [
	['Noel', '/noʊˈɛl/'],
	['The First Noel', '/ðə fˈɜːst noʊˈɛl/'],
	['Joyeux Noel', '/ʒwɑjˈʌ noʊˈɛl/'],
	['Joyeux Noël', '/ʒwɑjˈʌ noʊˈɛl/'],
	['Noël', '/noʊˈɛl/'],
	['Pere Noel', '/pˈɛɹ noʊˈɛl/'],
	['Père Noël', '/pˈɛɹ noʊˈɛl/'],
	['Papa Noel', '/pˈɑpə noʊˈɛl/'],
	['Yuletide', '/jˈuːltˌaɪd/'],
	['Emmanuel', '/ɪmˈænjuːˌɛl/'],
	['Whoville', '/hˈuːvɪl/'],
	['Cindy Lou Who', '/sˈɪndi lˈuː hˈuː/'],
	['Adeste Fideles', '/ɑdˈɛsteɪ fidˈeɪleɪs/'],
	['Gloria in Excelsis Deo', '/ɡlˈɔɹiə ɪn ɛkʃˈɛlsɪs dˈeɪoʊ/'],
	['In Excelsis Deo', '/ɪn ɛkʃˈɛlsɪs dˈeɪoʊ/'],
	['Ave Maria', '/ˈɑveɪ mɑɹˈiə/'],
	['Gesu Bambino', '/dʒeɪzˈuː bɑmbˈinoʊ/'],
	['Il est ne', '/ˌil ɛ nˈeɪ/'],
	['Il est né', '/ˌil ɛ nˈeɪ/'],
	['O Tannenbaum', '/ˈoʊ tˈɑnənbˌaʊm/'],
	['Tannenbaum', '/tˈɑnənbˌaʊm/'],
	['Stille Nacht', '/ʃtˈɪlə nˈɑxt/'],
	['fa la la la la', '/fˈɑ lɑ lɑ lɑ lˈɑ/'],
	['Weihnachtsmann', '/vˈaɪnɑxtsmɑn/'],
	['La Befana', '/lɑ beɪfˈɑnə/'],
	['Tomte', '/tˈɔmtə/'],
	['Julebukk', '/jˈuləbʊk/'],
	['St. Nick', 'Saint Nick'],
	['St. Nicholas', 'Saint Nicholas'],
	['St. Lucia', 'Saint Lucia'],
	['St. Stephen', 'Saint Stephen'],
	['Xmas', 'Christmas'],
	['Chanukah', '/hˈɑnəkə/'],
	['Kwanzaa', '/kwˈɑnzə/'],
	['Mele Kalikimaka', '/mˈɛleɪ kəlˌikimˈɑkə/'],
	['Feliz Navidad', '/fəlˈiz nˌɑvidˈɑd/'],
	['Navidad', '/nˌɑvidˈɑd/'],
	['Feliz', '/fəlˈiz/'],
	['Prospero Año Nuevo', '/pɹˈɔspɛɹoʊ ˈɑnjoʊ nwˈeɪvoʊ/'],
	['Prospero Ano Nuevo', '/pɹˈɔspɛɹoʊ ˈɑnjoʊ nwˈeɪvoʊ/'],
	['Año Nuevo', '/ˈɑnjoʊ nwˈeɪvoʊ/'],
	['Ano Nuevo', '/ˈɑnjoʊ nwˈeɪvoʊ/'],
	['Las Posadas', '/lɑs poʊsˈɑdɑs/'],
	['farolitos', '/fɑɹoʊlˈitoʊs/'],
	['piñata', '/pinjˈɑtə/'],
	['pinata', '/pinjˈɑtə/'],
	['jalapeño', '/hˌɑləpˈeɪnjoʊ/'],
	['jalapeno', '/hˌɑləpˈeɪnjoʊ/'],
	['Buon Natale', '/bwˈɔn nɑtˈɑleɪ/'],
	['Feliciano', '/fəlˌisiˈɑnoʊ/'],
	['Tchaikovsky', '/tʃaɪkˈɔfski/'],
	['Beyoncé', '/biˈjɑnseɪ/'],
	['Beyonce', '/biˈjɑnseɪ/'],
	['Bocelli', '/boʊtʃˈɛli/'],
	['Michael Bublé', '/mˈaɪkəl buːblˈeɪ/'],
	['Michael Buble', '/mˈaɪkəl buːblˈeɪ/'],
	['Bublé', '/buːblˈeɪ/'],
	['Buble', '/buːblˈeɪ/'],
	['Celine Dion', '/seɪlˈin diˈɔn/'],
	['Céline Dion', '/seɪlˈin diˈɔn/'],
	['Enya', '/ˈɛnjə/'],
	['Sia', '/sˈiːə/'],
	['Guaraldi', '/ɡwəɹˈɑldi/'],
	['Idina Menzel', '/ɪdˈinə mˈɛnzəl/'],
	['TSO', 'T S O'],
	['Wham!', 'Wham'],
	['FPP', 'F P P'],
	['LEDs', 'L E Dees'],
	['LED', 'L E D'],
	['DMX', 'D M X'],
	['HOA', 'H O A'],
	['WS2811', 'W S twenty-eight eleven'],
	['WS2812', 'W S twenty-eight twelve'],
	['xLights', 'X Lights'],
	['MPH', 'miles per hour'],
	['mph', 'miles per hour'],
	['p.m.', 'P M'],
	['a.m.', 'A M'],
	['No.', 'number'],
	['#1', 'number one'],
	['Mon.', 'Monday'],
	['Tue.', 'Tuesday'],
	['Tues.', 'Tuesday'],
	['Wed.', 'Wednesday'],
	['Thu.', 'Thursday'],
	['Thurs.', 'Thursday'],
	['Fri.', 'Friday'],
	['Sat.', 'Saturday'],
	['Sun.', 'Sunday'],
	['Jan.', 'January'],
	['Feb.', 'February'],
	['Aug.', 'August'],
	['Sept.', 'September'],
	['Oct.', 'October'],
	['Nov.', 'November'],
	['Dec.', 'December'],
	['approx.', 'approximately'],
	['hrs.', 'hours'],
	['mins.', 'minutes'],
	['min.', 'minutes'],
	['vs.', 'versus'],
	['w/', 'with'],
	['&', 'and']
];
